### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DeRus0**
General text optimizations. I thought this could benefit from a bit of rework. Hope you like it!

### CODE REVIEW

**Comment by sonu27** [comment]
Are you using a GPT model?

**Comment by DeRus0** [comment]
In this case, yes, it is not 100% copy paste, but most of my work was to shuffle sentences, replace words and make more meaningful paragraphs. Why do you ask? Is there any downside I am missing with this method?

**Comment by sonu27** [comment]
It doesn't fully understand and made some mistakes: `...not be duplicates. next, the images are annotated...`
And duplicated sentence at the bottom.

**Comment by DeRus0** [comment]
Oh that may be me, sorry about that

**Pull request closed without merging**
